-------------------
-- CONFIGURATION --
-------------------
OPEN_BAGS = true
FOLLOW_NORMAL = true
MIN_MONSTERS = 1
MAX_MONSTERS = 8
MyLevel = character:level()
AUTO_DELETE = { 884, 395, 385, 14687, 885, 881, 883, 887, 8545, 882, 14672, 304, 2419, 2425, 2422 }
----------------------
if ( MyLevel <= 18 ) then
    if (MyLevel <= 5) then MAX_MONSTERS= 2 end
    if (MyLevel <= 10) then MAX_MONSTERS= 4 end
    if (MyLevel <= 18) then MAX_MONSTERS= 8 end
    function move()
        return {
            --Tutorial deadline
            { map = "-5,-1", path = "bottom" },
            { map = "-4,0", path = "right" },
            { map = "-3,1", path = "right" },
            { map = "-2,2", path = "bottom" }, 
            { map = "80219143", path = "top(3)" },
            { map = "6,5", path = "top" },
            { map = "6,4", path = "top" },
            { map = "6,3", path = "left" },
            { map = "5,3", path = "left" },
            { map = "4,3", path = "left" },
            --Fight bucle
            { map = "0,3", fight = true, path = "top" },
            { map = "0,2", fight = true, path = "top" },
            { map = "0,1", fight = true, path = "top" },
            { map = "0,0", fight = true, path = "top" },
            { map = "0,-1", fight = true, path = "right" },
            { map = "1,3", fight = true, path = "right" },
            { map = "1,2", fight = true, path = "bottom" },
            { map = "1,1", fight = true, path = "bottom" },
            { map = "1,0", fight = true, path = "bottom" },
            { map = "1,-1", fight = true, path = "bottom" },
            { map = "2,3", fight = true, path = "top" },
            { map = "2,2", fight = true, path = "left|right|top|bottom" },
            { map = "2,1", fight = true, path = "left|right|top|bottom" },
            { map = "2,0", fight = true, path = "left|top" },
            { map = "2,-1", fight = true, path = "bottom(553)" },
            { map = "3,3", fight = true, path = "left(364)|top(5)" },
            { map = "3,2", fight = true, path = "left|top|bottom" },
            { map = "3,1", fight = true, path = "left|bottom" },
        }
    end
    function phenix()
        return {
            { map = "7,4", path = "left" },
            { map = "6,4", path = "bottom" },
            { map = "6,5", path = "bottom" },
            { map = "80219143", phenix = "176" },
        }
    end

elseif ( MyLevel >= 18 ) then
    function ToAstrub()
        npc:npc(888, 3)
        npc:reply(-1)
        npc:reply(-1) 
        global:printSuccess("We are on astrub")
    end
    function move()
        return {
            { map = "-5,-1", path = "bottom" },
            { map = "-4,0", path = "right" },
            { map = "-3,1", path = "right" },
            { map = "-2,2", path = "bottom" },
            { map = "0,3", path = "right" },
            { map = "0,2", path = "bottom" },
            { map = "0,1", path = "bottom" },
            { map = "0,0", path = "bottom" },
            { map = "0,-1", path = "bottom" },
            { map = "1,3", path = "right" },
            { map = "1,2", path = "bottom" },
            { map = "1,1", path = "bottom" },
            { map = "1,0", path = "bottom" },
            { map = "1,-1", path = "bottom" },
            { map = "2,3", path = "right" },
            { map = "2,2", path = "bottom" },
            { map = "2,1", path = "bottom" },
            { map = "2,0", path = "bottom" },
            { map = "2,-1", path = "bottom" },
            { map = "3,3", path = "right" },
            { map = "3,2", path = "bottom" },
            { map = "3,1", path = "bottom" },
            { map = "4,3", path = "top" },
            { map = "4,2", path = "right" },
            { map = "5,2", path = "right" },
            { map = "6,2", path = "right" },
            { map = "7,2", path = "right" },
            { map = "8,2", path = "bottom" },
            { map = "8,3", path = "right" },
            { map = "80220676", custom = ToAstrub },
        }
    end 
elseif ( MyLevel >= 18 ) then
    function move()
        return {
            { map = "-1,-21", path = "bottom" },
            { map = "-1,-20", path = "left" },
            { map = "-1,-19", path = "top" },
            { map = "-1,-18", path = "top" },
            { map = "-1,-17", path = "bottom" },
            { map = "-1,-16", path = "bottom" },
            { map = "-1,-15", path = "bottom" },
            { map = "-1,-14", path = "bottom" },
            { map = "0,-22", path = "bottom" },
            { map = "0,-21", path = "left|bottom" },
            { map = "0,-20", path = "left" },
            { map = "0,-19", path = "top|left" },
            { map = "0,-18", path = "top|left" },
            { map = "0,-17", path = "left|bottom" },
            { map = "0,-16", path = "left|bottom" },
            { map = "0,-15", path = "left" },
            { map = "0,-14", path = "left" },
            { map = "1,-22", path = "left" },
            { map = "1,-21", path = "left|bottom" },
            { map = "1,-20", path = "left" },
            { map = "1,-19", path = "top|left" },
            { map = "1,-18", path = "top|left" },
            { map = "1,-17", path = "left|bottom" },
            { map = "1,-16", path = "left|bottom" },
            { map = "1,-15", path = "left" },
            { map = "1,-14", path = "left" },
            { map = "2,-22", path = "left|right" },
            { map = "2,-21", path = "left|right" },
            { map = "2,-20", path = "left|right" },
            { map = "2,-19", path = "left|right" },
            { map = "2,-18", path = "left|right" },
            { map = "2,-17", path = "left|right" },
            { map = "2,-16", path = "left|right" },
            { map = "2,-15", path = "left" },
            { map = "2,-14", path = "left" },
            { map = "3,-22", path = "right" },
            { map = "3,-21", path = "right" },
            { map = "3,-20", path = "right" },
            { map = "3,-19", path = "top" },
            { map = "3,-18", path = "top" },
            { map = "3,-17", path = "top" },
            { map = "3,-16", path = "top" },
            { map = "3,-15", path = "left" },
            { map = "3,-14", path = "left" },
            { map = "4,-22", path = "right" },
            { map = "4,-21", path = "top|right" },
            { map = "4,-20", path = "top|right" },
            { map = "4,-19", path = "top|bottom" },
            { map = "4,-18", path = "bottom" },
            { map = "4,-17", path = "left|right" },
            { map = "5,-22", path = "top" },
            { map = "5,-21", path = "top" },
            { map = "5,-20", path = "top" },
            { map = "5,-19", path = "top" },
            { map = "5,-18", path = "top" },
            { map = "5,-17", path = "top" },
            { map = "5,-16", path = "top" },
            { map = "5,-15", path = "top" },
            { map = "6,-21", path = "left" },
            { map = "6,-20", path = "top|left|right" },
            { map = "6,-19", path = "top|left|right" },
            { map = "6,-18", path = "top|left|right" },
            { map = "6,-17", path = "top|left|right" },
            { map = "6,-16", path = "top|left|right" },
            { map = "6,-15", path = "top|left|right" },
            { map = "7,-15", path = "top" },
            { map = "7,-16", path = "top" },
            { map = "7,-17", path = "top" },
            { map = "7,-18", path = "top" },
            { map = "7,-19", path = "right" },
            { map = "7,-21", path = "left|bottom" },
            { map = "7,-20", path = "bottom" },
            { map = "2,-12", path = "top" },
            { map = "-3,-20", path = "right|bottom", fight = true },
            { map = "-3,-19", path = "top|right|bottom", fight = true },
            { map = "-3,-18", path = "top|right|bottom", fight = true },
            { map = "-3,-17", path = "top|right|bottom", fight = true },
            { map = "-3,-16", path = "top|right|bottom", fight = true },
            { map = "-3,-15", path = "top|right|bottom", fight = true },
            { map = "-3,-14", path = "top|right|bottom", fight = true },
            { map = "-3,-13", path = "top|right", fight = true },
            { map = "-2,-23", path = "right|bottom", fight = true },
            { map = "-2,-22", path = "top|right|bottom", fight = true },
            { map = "-2,-21", path = "top|bottom", fight = true },
            { map = "-2,-20", path = "top|left|bottom", fight = true },
            { map = "-2,-19", path = "top|left|bottom", fight = true },
            { map = "-2,-18", path = "top|left|bottom", fight = true },
            { map = "-2,-17", path = "top|left|bottom", fight = true },
            { map = "-2,-16", path = "top|left|bottom", fight = true },
            { map = "-2,-15", path = "top|left|bottom", fight = true },
            { map = "-2,-14", path = "top|left|bottom", fight = true },
            { map = "-2,-13", path = "top|left|right", fight = true },
            { map = "-1,-23", path = "left|right|bottom", fight = true },
            { map = "-1,-22", path = "top|left", fight = true },
            { map = "-1,-13", path = "left|right", fight = true },
            { map = "0,-23", path = "left|right", fight = true },
            { map = "0,-13", path = "left|right", fight = true },
            { map = "1,-23", path = "left|right", fight = true },
            { map = "1,-13", path = "left|right", fight = true },
            { map = "2,-23", path = "left|right", fight = true },
            { map = "2,-13", path = "left|right", fight = true },
            { map = "3,-23", path = "left|right", fight = true },
            { map = "3,-13", path = "left|right", fight = true },
            { map = "4,-23", path = "left|right", fight = true },
            { map = "4,-13", path = "left|right", fight = true },
            { map = "5,-23", path = "left|right", fight = true },
            { map = "5,-14", path = "right|bottom", fight = true },
            { map = "5,-13", path = "top|left|right", fight = true },
            { map = "6,-23", path = "left|right|bottom", fight = true },
            { map = "6,-22", path = "top|right", fight = true },
            { map = "6,-14", path = "left|right|bottom", fight = true },
            { map = "6,-13", path = "top|left|right", fight = true },
            { map = "7,-23", path = "left|right|bottom", fight = true },
            { map = "7,-22", path = "top|left|right", fight = true },
            { map = "7,-14", path = "left|right|bottom", fight = true },
            { map = "7,-13", path = "top|left|right", fight = true },
            { map = "8,-23", path = "left|bottom", fight = true },
            { map = "8,-22", path = "top|left|bottom", fight = true },
            { map = "8,-21", path = "top|bottom", fight = true },
            { map = "8,-20", path = "top|bottom", fight = true },
            { map = "8,-19", path = "top|bottom", fight = true },
            { map = "8,-18", path = "top|bottom", fight = true },
            { map = "8,-17", path = "top|bottom", fight = true },
            { map = "8,-16", path = "top|bottom", fight = true },
            { map = "8,-15", path = "top|bottom", fight = true },
            { map = "8,-14", path = "top|left|bottom", fight = true },
            { map = "8,-13", path = "top|left", fight = true },
            { map = "6,-24", path = "bottom" },
            { map = "7,-24", path = "bottom" },
            { map = "9,-23", path = "left" },
            { map = "8,-24", path = "bottom" },
            { map = "9,-22", path = "left" },
            { map = "9,-21", path = "left" },
            { map = "9,-20", path = "left" },
            { map = "9,-19", path = "left" },
            { map = "9,-18", path = "left" },
            { map = "9,-17", path = "left" },
            { map = "9,-16", path = "left" },
            { map = "9,-15", path = "left" },
            { map = "9,-14", path = "left" },
            { map = "8,-12", path = "top" },
            { map = "9,-13", path = "left" },
            { map = "7,-12", path = "top" },
            { map = "6,-12", path = "top" },
            { map = "5,-12", path = "top" },
            { map = "4,-12", path = "top" },
            { map = "3,-12", path = "top" },
            { map = "5,-24", path = "bottom" },
            { map = "4,-24", path = "bottom" },
            { map = "3,-24", path = "bottom" },
            { map = "2,-24", path = "bottom" },
            { map = "1,-24", path = "bottom" },
            { map = "1,-12", path = "top" },
            { map = "0,-12", path = "top" },
            { map = "0,-24", path = "bottom" },
            { map = "-1,-12", path = "top" },
            { map = "-1,-24", path = "bottom" },
            { map = "-2,-12", path = "top" },
            { map = "-3,-21", path = "right" },
            { map = "-3,-22", path = "right" },
            { map = "-3,-23", path = "right" },
            { map = "-2,-24", path = "bottom" },
            { map = "-3,-12", path = "top" },
            { map = "-4,-13", path = "right" },
            { map = "-4,-14", path = "right" },
            { map = "-4,-15", path = "right" },
            { map = "-4,-16", path = "right" },
            { map = "-4,-17", path = "right" },
            { map = "-4,-18", path = "right" },
            { map = "-4,-19", path = "right" },
            { map = "-4,-20", path = "right" },
            { map = "-3,-21", path = "bottom" },
            { map = "2,-11", path = "top" },
            { map = "3,-12", path = "left" },
            { map = "1,-12", path = "right" },
            { map = "8,-12", path = "top" },
            { map = "9,-13", path = "left" },
            { map = "9,-14", path = "left" },
            { map = "9,-15", path = "left" },
            { map = "9,-16", path = "left" },
            { map = "9,-17", path = "left" },
            { map = "9,-18", path = "left" },
            { map = "9,-19", path = "left" },
            { map = "9,-20", path = "left" },
            { map = "9,-21", path = "left" },
            { map = "9,-22", path = "left" },
            { map = "9,-23", path = "left" },
            { map = "8,-24", path = "bottom" },
            { map = "7,-12", path = "top" },
            { map = "7,-24", path = "bottom" },
            { map = "6,-12", path = "top" },
            { map = "6,-24", path = "bottom" },
            { map = "5,-12", path = "top" },
            { map = "5,-24", path = "bottom" },
            { map = "4,-12", path = "top" },
            { map = "4,-24", path = "bottom" },
            { map = "3,-12", path = "top" },
            { map = "3,-24", path = "bottom" },
            { map = "2,-24", path = "bottom" },
            { map = "1,-12", path = "top" },
            { map = "1,-24", path = "bottom" },
            { map = "0,-12", path = "top" },
            { map = "0,-24", path = "bottom" },
            { map = "-1,-12", path = "top" },
            { map = "-1,-24", path = "bottom" },
            { map = "-2,-12", path = "top" },
            { map = "-3,-21", path = "right" },
            { map = "-3,-22", path = "right" },
            { map = "-3,-23", path = "right" },
            { map = "-2,-24", path = "bottom" },
            { map = "-3,-12", path = "top" },
            { map = "-4,-13", path = "right" },
            { map = "-4,-14", path = "right" },
            { map = "-4,-15", path = "right" },
            { map = "-4,-16", path = "right" },
            { map = "-4,-17", path = "right" },
            { map = "-4,-18", path = "right" },
            { map = "-4,-19", path = "right" },
            { map = "-4,-20", path = "right" },
            { map = "-3,-21", path = "bottom" },
            { map = "84674566", path = "left|right" },
            { map = "83887104", path = "396" },
            }
    end 
    function bank()
        return {
            { map = "-3,-20", path = "right" },
            { map = "-3,-19", path = "right" },
            { map = "-3,-18", path = "right" },
            { map = "-3,-17", path = "right" },
            { map = "-3,-16", path = "right" },
            { map = "-3,-15", path = "right" },
            { map = "-3,-14", path = "right" },
            { map = "-3,-13", path = "right" },
            { map = "-2,-23", path = "bottom" },
            { map = "-2,-22", path = "bottom" },
            { map = "-2,-21", path = "bottom" },
            { map = "-2,-19", path = "right" },
            { map = "-2,-18", path = "top" },
            { map = "-2,-17", path = "top" },
            { map = "-2,-16", path = "top" },
            { map = "-2,-15", path = "bottom" },
            { map = "-2,-14", path = "bottom" },
            { map = "-2,-13", path = "right" },
            { map = "-1,-23", path = "left" },
            { map = "-1,-22", path = "left" },
            { map = "-1,-21", path = "right" },
            { map = "-1,-20", path = "right" },
            { map = "-1,-19", path = "right" },
            { map = "-1,-18", path = "right" },
            { map = "-1,-17", path = "right" },
            { map = "-1,-16", path = "right" },
            { map = "-1,-15", path = "top" },
            { map = "-1,-14", path = "top" },
            { map = "-1,-13", path = "top" },
            { map = "0,-23", path = "left" },
            { map = "0,-22", path = "right" },
            { map = "0,-21", path = "right" },
            { map = "0,-20", path = "right" },
            { map = "0,-19", path = "right" },
            { map = "0,-18", path = "right" },
            { map = "0,-17", path = "right" },
            { map = "0,-16", path = "right" },
            { map = "0,-15", path = "right" },
            { map = "0,-14", path = "right" },
            { map = "0,-13", path = "right" },
            { map = "1,-22", path = "bottom" },
            { map = "1,-21", path = "bottom" },
            { map = "1,-20", path = "bottom" },
            { map = "1,-19", path = "right" },
            { map = "1,-18", path = "bottom" },
            { map = "1,-17", path = "bottom" },
            { map = "1,-16", path = "right" },
            { map = "1,-15", path = "top" },
            { map = "1,-14", path = "top" },
            { map = "2,-22", path = "bottom" },
            { map = "2,-21", path = "bottom" },
            { map = "2,-20", path = "bottom" },
            { map = "2,-19", path = "bottom" },
            { map = "2,-18", path = "right" },
            { map = "2,-17", path = "right" },
            { map = "2,-16", path = "right" },
            { map = "2,-15", path = "top" },
            { map = "2,-14", path = "top" },
            { map = "1,-13", path = "right" },
            { map = "2,-13", path = "right" },
            { map = "1,-23", path = "right" },
            { map = "2,-23", path = "right" },
            { map = "3,-23", path = "right" },
            { map = "4,-23", path = "right" },
            { map = "5,-23", path = "bottom" },
            { map = "5,-22", path = "bottom" },
            { map = "5,-21", path = "bottom" },
            { map = "5,-20", path = "bottom" },
            { map = "5,-19", path = "bottom" },
            { map = "5,-18", path = "bottom" },
            { map = "5,-17", path = "bottom" },
            { map = "5,-16", path = "left" },
            { map = "3,-22", path = "bottom" },
            { map = "3,-21", path = "bottom" },
            { map = "3,-20", path = "bottom" },
            { map = "3,-19", path = "bottom" },
            { map = "3,-18", path = "bottom" },
            { map = "3,-17", path = "bottom" },
            { map = "4,-22", path = "left" },
            { map = "4,-21", path = "left" },
            { map = "4,-20", path = "left" },
            { map = "4,-19", path = "left" },
            { map = "3,-16", path = "right" },
            { map = "3,-15", path = "top" },
            { map = "3,-13", path = "right" },
            { map = "4,-13", path = "top" },
            { map = "4,-14", path = "top" },
            { map = "4,-15", path = "top" },
            { map = "3,-14", path = "top" },
            { map = "5,-14", path = "left" },
            { map = "5,-13", path = "left" },
            { map = "6,-13", path = "left" },
            { map = "6,-14", path = "left" },
            { map = "7,-14", path = "left" },
            { map = "7,-13", path = "left" },
            { map = "8,-13", path = "left" },
            { map = "8,-14", path = "left" },
            { map = "8,-15", path = "bottom" },
            { map = "8,-16", path = "bottom" },
            { map = "8,-17", path = "top" },
            { map = "8,-18", path = "top" },
            { map = "8,-19", path = "left" },
            { map = "8,-20", path = "bottom" },
            { map = "8,-21", path = "bottom" },
            { map = "8,-22", path = "bottom" },
            { map = "8,-23", path = "bottom" },
            { map = "7,-23", path = "bottom" },
            { map = "7,-22", path = "right" },
            { map = "6,-23", path = "left" },
            { map = "6,-22", path = "top" },
            { map = "7,-19", path = "left" },
            { map = "6,-19", path = "left" },
            { map = "6,-21", path = "left" },
            { map = "7,-21", path = "left" },
            { map = "7,-20", path = "left" },
            { map = "6,-20", path = "left" },
            { map = "6,-18", path = "left" },
            { map = "7,-18", path = "left" },
            { map = "7,-17", path = "left" },
            { map = "6,-17", path = "left" },
            { map = "6,-16", path = "left" },
            { map = "7,-16", path = "left" },
            { map = "7,-15", path = "left" },
            { map = "6,-15", path = "left" },
            { map = "5,-15", path = "top" },
            { map = "84674566", door = "303" }, -- Map ext�rieure de la banque
            { map = "83887104", npcBank = true, path = "396" }, -- Map int�rieure de la banque
        }
    end   
    function phenix()
        return {
            { map = "-3,-11", path = "right" },
            { map = "-2,-11", path = "right" },
            { map = "-1,-11", path = "right" },
            { map = "0,-11", path = "top" },
            { map = "0,-12", path = "top" },
            { map = "0,-13", path = "right" },
            { map = "1,-13", path = "right" },
            { map = "2,-13", path = "bottom" },
            { map = "84673546", phenix = "272" },
        }
    end
end
