--#####################--
--## Scripted by: RevKTL
--## Purpose: Fighting
--## version: 0.1
--## Comments:
--#####################--
-- CONFIGURATION & VARIABLES --
MAX_MONSTERS = 1
MIN_MONSTERS = 2
FORCE_MONSTERS = {}
FORBIDDEN_MONSTERS = {}
AUTO_DELETE = {}
MyLevel = character:level()

if MyLevel < 65 then
    if (MyLevel <= 45) then MAX_MONSTERS= 4 end
    if (MyLevel >= 55) then MAX_MONSTERS= 8 end
    if (MyLevel >= 65) then MAX_MONSTERS= 8 end
    function move()
        return{
            { map= "10,19", path= "bottom" },
            { map= "10,20", path= "left" },
            { map= "9,20", path= "left" },
            { map= "8,20", path= "left" },
            { map= "7,20", path= "left" },
            { map= "6,20", path= "left" },
            { map= "5,20", path= "left" },
            { map= "4,20", path= "left" },
            { map= "3,20", path= "bottom" },
            { map= "3,21", path= "bottom" },
            { map= "4,22", fight= true, path= "left" },
            { map= "3,22", fight= true, path= "left|right" },
            { map= "2,22", fight= true, path= "left|right" },
            { map= "1,22", fight= true, path= "right|bottom" },
            { map= "1,23", fight= true, path= "right|top" },
            { map= "2,23", fight= true, path= "left|right" },
            { map= "3,23", fight= true, path= "bottom|left" },
            { map= "3,24", fight= true, path= "top|bottom" },
            { map= "3,25", fight= true, path= "left|top" },
            { map= "2,25", fight= true, path= "left|right" },
            { map= "1,26", path= "left|top" },
            { map= "2,26", path= "top" },
            { map= "3,26", path= "top" },
            { map= "4,26", path= "top" },
            { map= "4,25", path= "left" },
            { map= "4,24", path= "left" },
            { map= "4,23", path= "left" },
            { map= "1,25", path= "right" },
            { map= "1,24", path= "right" },
            { map= "2,24", path= "bottom|top" },
            { map= "0,24", path= "right" },
            { map= "0,23", path= "right" },
            { map= "-1,23", path= "right" },
            { map= "-1,24", path= "right" },
            { map= "1,21", path= "bottom" },
            { map= "2,21", path= "bottom" },
            { map= "3,21", path= "bottom" },
            { map= "4,21", path= "bottom" },
            { map= "5,21", path= "bottom" },
            { map= "5,22", path= "left" },
            { map= "4,-19", path= "zaap(88212481)" },
            { map= "4,-18", path= "top" },
            { map= "4,-17", path= "top" },
            { map= 84674566, path= "top" },
            { map= "0,-15", path= "top" },
            { map= "1,-15", path= "top" },
            { map= "2,-15", path= "top" },
            { map= "3,-15", path= "top" },
            { map= "4,-15", path= "top" },
            { map= "5,-15", path= "top" },
            { map= "6,-15", path= "top" },
            { map= "7,-16", path= "left" },
            { map= "7,-17", path= "left" },
            { map= "7,-18", path= "left" },
            { map= "7,-19", path= "left" },
            { map= "7,-20", path= "left" },
            { map= "7,-21", path= "left" },
            { map= "6,-21", path= "left|bottom" },
            { map= "5,-21", path= "left|bottom" },
            { map= "4,-21", path= "left|bottom" },
            { map= "3,-21", path= "left|bottom|right" },
            { map= "2,-21", path= "right|bottom" },
            { map= "1,-21", path= "right|bottom" },
            { map= "1,-20", path= "right" },
            { map= "2,-20", path= "right" },
            { map= "3,-20", path= "right" },
            { map= "4,-20", path= "bottom" },
            { map= "6,-20", path= "left" },
            { map= "5,-20", path= "left" },
            { map= "6,-19", path= "left" },
            { map= "5,-19", path= "left" },
            { map= "6,-18", path= "left" },
            { map= "5,-18", path= "left" },
            { map= "6,-17", path= "left" },
            { map= "5,-17", path= "left" },
            { map= "-1,-16", path= "right" },
            { map= "-1,-15", path= "right" },
            { map= "0,-16", path= "right" },
            { map= "1,-16", path= "right" },
            { map= "2,-16", path= "right" },
            { map= "3,-16", path= "right" },
            { map= "0,-17", path= "right" },
            { map= "1,-17", path= "right" },
            { map= "2,-17", path= "right" },
            { map= "3,-17", path= "right" },
            { map= "-1,-17", path= "right" },
            { map= "-1,-18", path= "right" },
            { map= "0,-18", path= "right" },
            { map= "1,-18", path= "right" },
            { map= "2,-18", path= "right" },
            { map= "3,-18", path= "right" },
            { map= "-1,-19", path= "right" },
            { map= "0,-19", path= "right" },
            { map= "1,-19", path= "right" },
            { map= "2,-19", path= "right" },
            { map= "3,-19", path= "right" },
            { map= "-1,-20", path= "right" },
            { map= "0,-20", path= "right" },
            { map= "-1,-21", path= "right" },
            { map= "0,-21", path= "right|bottom" },
            { map= "4,-22", path= "bottom" },
            { map= "5,-22", path= "bottom" },
            { map= "3,-22", path= "bottom" },
            { map= "2,-22", path= "bottom" },
            { map= "1,-22", path= "bottom" },
            { map= "0,-22", path= "bottom" },
            { map= "0,-14", path= "top" },
            { map= "-1,-14", path= "top" },
            { map= "1,-14", path= "top" },
            { map= "2,-14", path= "top" },
            { map= "3,-14", path= "top" },
            { map= "4,-14", path= "top" },
            { map= 83887104, path= "396" },
        }
    end
    function bank()
        return {
            { map= "4,22", path= "left" },
            { map= "3,22", path= "bottom" },
            { map= "2,22", path= "bottom" },
            { map= "1,22", path= "bottom" },
            { map= "1,23", path= "left|bottom" },
            { map= "2,23", path= "left|bottom" },
            { map= "3,23", path= "left|bottom" },
            { map= "3,24", path= "left" },
            { map= "3,25", path= "left" },
            { map= "2,25", path= "top" },
            { map= "4,25", path= "left" },
            { map= "4,24", path= "left" },
            { map= "4,23", path= "left" },
            { map= "1,24", path= "left" },
            { map= "2,24", path= "left" },
            { map= "0,24", path= "left" },
            { map= "0,23", path= "left|bottom" },
            { map= "-1,23", path= "bottom" },
            { map= "-1,24", path= "zaap(84674563)" },
            { map= "1,21", path= "bottom" },
            { map= "2,21", path= "bottom" },
            { map= "3,21", path= "bottom" },
            { map= "4,21", path= "bottom" },
            { map= "5,21", path= "bottom" },
            { map= "5,22", path= "left" },
            { map= "4,-18", path= "bottom" },
            { map= "4,-19", path= "bottom" },
            { map= "4,-17", path= "bottom" },
            { map= "5,23", path= "left" },
            { map= 84674566, door= 303 },
            { map= 83887104, npcBank= true , path= "396" },
        }
    end
    function phenix()
        return{
                { map= "9,16", path= "right" },
                { map= "10,16", path= "right" },
                { map= "11,16", path= "right" },
                { map= "12,16", path= "right" },
                { map= "13,16", path= "bottom" },
                { map= "13,17", path= "bottom" },
                { map= "13,18", path= "bottom" },
                { map= "13,19", path= "bottom" },
                { map= "13,20", path= "left" },
                { map= "12,20", path= "left" },
                { map= "11,20", path= "top" },
                { map= "11,19", path= "left" },
                { map= 88085252, phenix= 192 },
        }
    end
end